apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
  - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels: 
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
   matchLabels:
     app: wordpress
     tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
       containers:
       - image: mysql
         name: mysql
         env:
         - name: MYSQL_ROOT_PASSWORD
           
           valueFrom:
             secretKeyRef:
              name: mysql-pass
              key: password
         - name: MYSQL_USER
           value: prajwal
         - name: MYSQL_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysqluser-pass
               key: password
         - name: MYSQL_DATABASE
           value: mydb
         ports:
         - containerPort: 3306
           name: mysql
         volumeMounts:
         - name: mysql-ps
           mountPath: /var/lib/mysql
       volumes:
       - name: mysql-ps
         persistentVolumeClaim:
           claimName: mysql-pv-claim